# Group Templates
## Templates [/template]

### Get the current list of templates [GET]
Get the full list of templates with all their associated attributes
+ Request
  + Headers
    Authorization: Bearer JWT
+ Response 200 (application/json)
  {
    "pagination": {
      "has_next": false,
      "next_page": null,
      "page": 1,
      "total": 1
    },
    "templates": [
      {
        "attrs": [
          {
            "created": "2017-10-09T18:58:06.560734+00:00",
            "id": 1,
            "label": "attr.a",
            "template_id": "1",
            "type": "dynamic",
            "value_type": "string"
          },
          {
            "created": "2017-10-09T18:58:06.562147+00:00",
            "id": 2,
            "label": "attr.b",
            "template_id": "1",
            "type": "dynamic",
            "value_type": "string"
          }
        ],
        "created": "2017-10-09T18:58:06.558058+00:00",
        "id": 1,
        "label": "test_template"
      },
      {
        "attrs": [
          {
            "created": "2017-10-09T18:58:08.587078+00:00",
            "id": 5,
            "label": "attr.a",
            "template_id": "3",
            "type": "dynamic",
            "value_type": "string"
          },
          {
            "created": "2017-10-09T18:58:08.587522+00:00",
            "id": 6,
            "label": "attr.b",
            "template_id": "3",
            "type": "dynamic",
            "value_type": "string"
          }
        ],
        "created": "2017-10-09T18:58:08.586395+00:00",
        "id": 3,
        "label": "test_template"
      },
      {
        "attrs": [
          {
            "created": "2017-10-09T19:12:40.176937+00:00",
            "id": 11,
            "label": "attr.a",
            "template_id": "4",
            "type": "dynamic",
            "updated": "2017-10-09T19:13:31.138364+00:00",
            "value_type": "string"
          },
          {
            "created": "2017-10-09T19:12:40.177666+00:00",
            "id": 12,
            "label": "attr.b",
            "static_value": "qwer",
            "template_id": "4",
            "type": "meta",
            "updated": "2017-10-09T19:13:31.138995+00:00",
            "value_type": "mapping"
          }
        ],
        "created": "2017-10-09T19:02:47.462534+00:00",
        "id": 4,
        "label": "test_template_upd",
        "updated": "2017-10-09T19:12:40.175548+00:00"
      }
    ]
  }


### Register a new template [POST]
Register a new template
+ Request
  + Headers
    Authorization: Bearer JWT
  + Body (application/json)
    {
      "label": "test_template",
      "attrs": [
        {"label":"attr.a","type":"dynamic","value_type":"string"},
        {"label":"attr.b","type":"dynamic","value_type":"string"}
      ]
    }
+ Response 200 (application/json)
  {
  "result": "ok",
  "template": {
    "attrs": [
      {
        "created": "2017-10-09T19:02:47.463580+00:00",
        "id": 7,
        "label": "attr.a",
        "template_id": "4",
        "type": "dynamic",
        "value_type": "string"
      },
      {
        "created": "2017-10-09T19:02:47.464119+00:00",
        "id": 8,
        "label": "attr.b",
        "template_id": "4",
        "type": "dynamic",
        "value_type": "string"
      }
    ],
    "created": "2017-10-09T19:02:47.462534+00:00",
    "id": 4,
    "label": "test_template"
  }
}
+ Response 400 (application/json)
  {
    "errors": {
        "label": [
            "Missing data for required field."
        ]
    },
    "message": "failed to parse input"
  }

## Template info [/template/{id}]
Access a specific template
+ parameters
  + id: (required, string) - The template ID


### Delete template [DELETE]
Removes a template
+ Response 200 (application/json)
  {
    "removed": {
      "attrs": [
        {
          "created": "2017-10-09T18:58:07.681866+00:00",
          "id": 3,
          "label": "attr.a",
          "template_id": "2",
          "type": "dynamic",
          "value_type": "string"
        },
        {
          "created": "2017-10-09T18:58:07.682231+00:00",
          "id": 4,
          "label": "attr.b",
          "template_id": "2",
          "type": "dynamic",
          "value_type": "string"
        }
      ],
      "created": "2017-10-09T18:58:07.681183+00:00",
      "id": 2,
      "label": "test_template"
    },
    "result": "ok"
  }
+ Response 404 (application/json)
  {
    "message": "No such template: 123",
    "status": 404
  }

### Get template info [GET]
Retrieves all information from a specific template
+ Response 200 (application/json)
  {
  "attrs": [
    {
      "created": "2017-10-09T18:58:06.560734+00:00",
      "id": 1,
      "label": "attr.a",
      "template_id": "1",
      "type": "dynamic",
      "value_type": "string"
    },
    {
      "created": "2017-10-09T18:58:06.562147+00:00",
      "id": 2,
      "label": "attr.b",
      "template_id": "1",
      "type": "dynamic",
      "value_type": "string"
    }
  ],
  "created": "2017-10-09T18:58:06.558058+00:00",
  "id": 1,
  "label": "test_template"
}
+ Response 404 (application/json)
  {
    "message": "No such template: 123",
    "status": 404
  }
### Update template info [PUT]
Replaces all attributes from a specific template
+ Response 200 (application/json)
  {
    "result": "ok",
    "updated": {
      "attrs": [
        {
          "created": "2017-10-09T19:12:40.176937+00:00",
          "id": 11,
          "label": "attr.a",
          "template_id": "4",
          "type": "dynamic",
          "value_type": "string"
        },
        {
          "created": "2017-10-09T19:12:40.177666+00:00",
          "id": 12,
          "label": "attr.b",
          "static_value": "asdf",
          "template_id": "4",
          "type": "meta",
          "value_type": "mapping"
        }
      ],
      "created": "2017-10-09T19:02:47.462534+00:00",
      "id": 4,
      "label": "test_template_upd",
      "updated": "2017-10-09T19:12:40.175548+00:00"
    }
  }
+ Response 404 (application/json)
  {
    "message": "No such template: 123",
    "status": 404
  }
