"""empty message

Revision ID: fabf2ca39860
Revises: 6beff7876a3a
Create Date: 2018-04-16 15:43:09.997566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabf2ca39860'
down_revision = '6beff7876a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pre_shared_keys',
    sa.Column('attr_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=8), nullable=False),
    sa.Column('psk', sa.Binary(), nullable=False),
    sa.ForeignKeyConstraint(['attr_id'], ['attrs.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('attr_id', 'device_id')
    )
    op.create_unique_constraint(None, 'devices', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_table('pre_shared_keys')
    # ### end Alembic commands ###
